project:
  type: website
  output-dir: docs

website:
  site-url: https://melandri-lab.github.io/
  #title: "Melandri Lab"
  
  #google-analytics: 
    #tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    #anonymize-ip: true
    
  favicon: img/sun_favicon.svg

  navbar:
    logo: img/logo_rectangular2.svg
    logo-alt: "Melandri Lab"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: gallery.qmd
        text: Gallery
      - icon: envelope
        href: mailto:gmelandri@arizona.edu
      
  page-footer: 
    left: Copyright 2023, Melandri Lab
    right:
      - text: "Google Scholar"
        url: "https://scholar.google.com/citations?user=8zWCTkUAAAAJ&hl=en"
      - text: "Research Gate"
        url: "https://www.researchgate.net/profile/Giovanni-Melandri-2"
      - text: Twitter
        icon: twitter
        url: "https://twitter.com/GiovanniMeland1"
    

format:
  html:
    theme: custom.scss
    toc: true
    page-layout: full

editor: visual

