project:
  type: website
  output-dir: docs

website:
  site-url: https://melandri-lab.github.io/
  #title: ""
  
  #google-analytics: 
    #tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    #anonymize-ip: true
    
  favicon: img/sun_favicon.svg

  navbar:
    logo: img/logo_rectangular.svg
    logo-alt: "Melandri Lab"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
  page-footer: 
    left: Copyright 2023, Melandri Lab
    

format:
  html:
    theme: custom.scss
    toc: true
    page-layout: full

editor: visual

